# Step 3 — KPI Implementation & Analysis

**Goal:** answer the brief's business questions on the clean data:

1. Best/worst performers (revenue, budget, profit, ROI, votes, rating, popularity)
2. Two advanced search queries
3. Franchise vs. standalone performance
4. Most successful franchises and directors


It reads from `data/processed/`.

In [113]:
import sys

import numpy as np
import pandas as pd

sys.path.append("..")
from src.analysis import add_financial_metrics, rank_movies

movies = pd.read_csv("../data/processed/movies_clean.csv", parse_dates=["release_date"])
movies = add_financial_metrics(movies)   # adds profit_musd and roi
movies[["title", "budget_musd", "revenue_musd", "profit_musd", "roi"]].head()

,title,budget_musd,revenue_musd,profit_musd,roi
0,Avengers: Endgame,356.0,2799.439100,2443.439100,7.863593
1,Avatar,237.0,2923.706026,2686.706026,12.336312
2,Star Wars: The Force Awakens,245.0,2068.223624,1823.223624,8.441729
3,Avengers: Infinity War,300.0,2052.415039,1752.415039,6.841383
4,Titanic,200.0,2264.162353,2064.162353,11.320812

## 3.1 Best & worst performers  

`rank_movies` (in `src/analysis.py`)  plays a major role in every question
  below is *one call* — filters included.

In [114]:
show = ["title", "budget_musd", "revenue_musd", "profit_musd", "roi", "vote_average", "popularity"]

print("Highest revenue:")
rank_movies(movies, by="revenue_musd", top_n=5)[show]

Highest revenue:

,title,budget_musd,revenue_musd,profit_musd,roi,vote_average,popularity
1,Avatar,237.0,2923.706026,2686.706026,12.336312,7.609,23.9453
0,Avengers: Endgame,356.0,2799.439100,2443.439100,7.863593,8.239,22.5075
4,Titanic,200.0,2264.162353,2064.162353,11.320812,7.900,25.7898
2,Star Wars: The Force Awakens,245.0,2068.223624,1823.223624,8.441729,7.248,10.1950
3,Avengers: Infinity War,300.0,2052.415039,1752.415039,6.841383,8.239,36.1995

In [115]:
print("Highest budget:")
rank_movies(movies, by="budget_musd", top_n=5)[show]

Highest budget:

,title,budget_musd,revenue_musd,profit_musd,roi,vote_average,popularity
0,Avengers: Endgame,356.0,2799.439100,2443.439100,7.863593,8.239,22.5075
3,Avengers: Infinity War,300.0,2052.415039,1752.415039,6.841383,8.239,36.1995
12,Star Wars: The Last Jedi,300.0,1334.407706,1034.407706,4.448026,6.747,21.5986
6,The Lion King,260.0,1662.020819,1402.020819,6.392388,7.096,12.8123
2,Star Wars: The Force Awakens,245.0,2068.223624,1823.223624,8.441729,7.248,10.1950

In [116]:
print("Highest profit:")
rank_movies(movies, by="profit_musd", top_n=5)[show]

Highest profit:

,title,budget_musd,revenue_musd,profit_musd,roi,vote_average,popularity
1,Avatar,237.0,2923.706026,2686.706026,12.336312,7.609,23.9453
0,Avengers: Endgame,356.0,2799.439100,2443.439100,7.863593,8.239,22.5075
4,Titanic,200.0,2264.162353,2064.162353,11.320812,7.900,25.7898
2,Star Wars: The Force Awakens,245.0,2068.223624,1823.223624,8.441729,7.248,10.1950
3,Avengers: Infinity War,300.0,2052.415039,1752.415039,6.841383,8.239,36.1995

In [117]:
print("Lowest profit:")
rank_movies(movies, by="profit_musd", top_n=5, ascending=True)[show]

Lowest profit:

,title,budget_musd,revenue_musd,profit_musd,roi,vote_average,popularity
12,Star Wars: The Last Jedi,300.0,1334.407706,1034.407706,4.448026,6.747,21.5986
17,Incredibles 2,200.0,1243.225667,1043.225667,6.216128,7.454,11.5637
16,Beauty and the Beast,160.0,1266.115964,1106.115964,7.913225,6.967,13.8312
15,Frozen,150.0,1274.219009,1124.219009,8.494793,7.249,20.1250
14,Jurassic World: Fallen Kingdom,170.0,1310.469037,1140.469037,7.708641,6.531,10.7329

In [118]:
print("Highest ROI (budget \u2265 10M):")
rank_movies(movies, by="roi", top_n=5, min_budget=10)[show]

Highest ROI (budget ≥ 10M):

,title,budget_musd,revenue_musd,profit_musd,roi,vote_average,popularity
1,Avatar,237.0,2923.706026,2686.706026,12.336312,7.609,23.9453
4,Titanic,200.0,2264.162353,2064.162353,11.320812,7.900,25.7898
5,Jurassic World,150.0,1671.537444,1521.537444,11.143583,6.700,16.0703
11,Harry Potter and the Deathly Hallows: Part 2,125.0,1341.511219,1216.511219,10.732090,8.080,17.5841
13,Frozen II,150.0,1453.683476,1303.683476,9.691223,7.229,19.1438

In [119]:
print("Lowest ROI (budget \u2265 10M):")
rank_movies(movies, by="roi", top_n=5, min_budget=10, ascending=True)[show]

Lowest ROI (budget ≥ 10M):

,title,budget_musd,revenue_musd,profit_musd,roi,vote_average,popularity
12,Star Wars: The Last Jedi,300.0,1334.407706,1034.407706,4.448026,6.747,21.5986
9,Avengers: Age of Ultron,235.0,1405.403694,1170.403694,5.980441,7.275,18.6554
17,Incredibles 2,200.0,1243.225667,1043.225667,6.216128,7.454,11.5637
6,The Lion King,260.0,1662.020819,1402.020819,6.392388,7.096,12.8123
10,Black Panther,200.0,1349.926083,1149.926083,6.749630,7.364,13.4733

In [120]:
print("Most voted:")
rank_movies(movies, by="vote_count", top_n=5)[["title", "vote_count", "vote_average"]]

Most voted:

                    title  vote_count  vote_average
7            The Avengers       38783         8.057
1                  Avatar       34232         7.609
3  Avengers: Infinity War       32293         8.239
0       Avengers: Endgame       28036         8.239
4                 Titanic       27357         7.900

In [121]:
print("Highest rated (\u2265 10 votes):")
rank_movies(movies, by="vote_average", top_n=5, min_votes=10)[["title", "vote_average", "vote_count"]]

Highest rated (≥ 10 votes):

                                           title  vote_average  vote_count
0                              Avengers: Endgame         8.239       28036
3                         Avengers: Infinity War         8.239       32293
11  Harry Potter and the Deathly Hallows: Part 2         8.080       22137
7                                   The Avengers         8.057       38783
4                                        Titanic         7.900       27357

In [122]:
print("Lowest rated (\u2265 10 votes):")
rank_movies(movies, by="vote_average", top_n=5, min_votes=10, ascending=True)[["title", "vote_average", "vote_count"]]

Lowest rated (≥ 10 votes):

                             title  vote_average  vote_count
14  Jurassic World: Fallen Kingdom         6.531       12851
5                   Jurassic World         6.700       21689
12        Star Wars: The Last Jedi         6.747       16443
16            Beauty and the Beast         6.967       16065
6                    The Lion King         7.096       10798

In [123]:
print("Most popular:")
rank_movies(movies, by="popularity", top_n=5)[["title", "popularity", "vote_average"]]

Most popular:

                    title  popularity  vote_average
3  Avengers: Infinity War     36.1995         8.239
7            The Avengers     35.0349         8.057
4                 Titanic     25.7898         7.900
1                  Avatar     23.9453         7.609
0       Avengers: Endgame     22.5075         8.239

## 3.2 Advanced search queries

Because we flattened genres and cast into `|`-separated strings, filtering is
vectorized string matching: **`.str.contains()`** gives a boolean mask per row,
and `&` combines masks. `na=False` says "a missing value is not a match"
(without it, NaN cells would poison the mask).

>  Our 18
> ids are all modern blockbusters — none stars Bruce Willis or Uma Thurman. The
> point is that the *query logic* is correct and reusable on any larger dataset.

In [124]:
# Search 1: Sci-Fi Action movies starring Bruce Willis, best-rated first
search_1 = movies[
    movies["genres"].str.contains("Science Fiction", na=False)
    & movies["genres"].str.contains("Action", na=False)
    & movies["cast"].str.contains("Bruce Willis", na=False)
].sort_values("vote_average", ascending=False)

print(f"{len(search_1)} matches")
search_1[["title", "genres", "vote_average"]]

0 matches

Empty DataFrame
Columns: [title, genres, vote_average]
Index: []

In [125]:
# Search 2: Uma Thurman movies directed by Quentin Tarantino, shortest first
# (.str.contains rather than == because 'director' can hold co-directors: 'A|B')
search_2 = movies[
    movies["cast"].str.contains("Uma Thurman", na=False)
    & movies["director"].str.contains("Quentin Tarantino", na=False)
].sort_values("runtime", ascending=True)

print(f"{len(search_2)} matches")
search_2[["title", "director", "runtime"]]

0 matches

Empty DataFrame
Columns: [title, director, runtime]
Index: []

In [126]:
# Proof the pattern works — same query shape, people who ARE in our data:
check = movies[
    movies["genres"].str.contains("Action", na=False)
    & movies["cast"].str.contains("Robert Downey Jr.", na=False)
].sort_values("vote_average", ascending=False)
check[["title", "vote_average"]]

                     title  vote_average
0        Avengers: Endgame         8.239
3   Avengers: Infinity War         8.239
7             The Avengers         8.057
9  Avengers: Age of Ultron         7.275

## 3.3 Franchise vs. standalone performance

This is done with **`groupby`**. The recipe is
*split → apply → combine*: split rows into groups, apply an aggregation to each,
combine into a summary table.

<!-- First we need a grouping key: franchise membership is simply "does
`belongs_to_collection` have a value?" -->

In [127]:
movies["franchise"] = np.where(movies["belongs_to_collection"].notna(), "Franchise", "Standalone")
movies["franchise"].value_counts()

franchise
Franchise     16
Standalone     2
Name: count, dtype: int64

In [128]:
franchise_vs_standalone = movies.groupby("franchise").agg(
    mean_revenue=("revenue_musd", "mean"),
    median_roi=("roi", "median"),
    mean_budget=("budget_musd", "mean"),
    mean_popularity=("popularity", "mean"),
    mean_rating=("vote_average", "mean"),
).round(2)

franchise_vs_standalone

,mean_revenue,median_roi,mean_budget,mean_popularity,mean_rating
franchise,,,,,
Franchise,1682.78,7.79,218.0,18.71,7.40
Standalone,1765.14,9.62,180.0,19.81,7.43

## 3.4 Most successful franchises

In [129]:
top_franchises = (
    movies.dropna(subset=["belongs_to_collection"])
    .groupby("belongs_to_collection")
    .agg(
        num_movies=("id", "count"),
        total_budget=("budget_musd", "sum"),
        mean_budget=("budget_musd", "mean"),
        total_revenue=("revenue_musd", "sum"),
        mean_revenue=("revenue_musd", "mean"),
        mean_rating=("vote_average", "mean"),
    )
    .sort_values("total_revenue", ascending=False)
    .round(2)
)
top_franchises

,num_movies,total_budget,mean_budget,total_revenue,mean_revenue,mean_rating
belongs_to_collection,,,,,,
The Avengers Collection,4,1111.0,277.75,7776.07,1944.02,7.95
Star Wars Collection,2,545.0,272.50,3402.63,1701.32,7.00
Jurassic Park Collection,2,320.0,160.00,2982.01,1491.00,6.62
Avatar Collection,1,237.0,237.00,2923.71,2923.71,7.61
Frozen Collection,2,300.0,150.00,2727.90,1363.95,7.24
The Lion King (Reboot) Collection,1,260.0,260.00,1662.02,1662.02,7.10
The Fast and the Furious Collection,1,190.0,190.00,1515.40,1515.40,7.22
Black Panther Collection,1,200.0,200.00,1349.93,1349.93,7.36
Harry Potter Collection,1,125.0,125.00,1341.51,1341.51,8.08
The Incredibles Collection,1,200.0,200.00,1243.23,1243.23,7.45

## 3.5 Most successful directors

 Four of our movies are co-directed  both
Avengers films (Joe & Anthony Russo) and both Frozen films (Chris Buck &
Jennifer Lee), so `director` holds e.g. `'Joe Russo|Anthony Russo'`. A naive
`groupby("director")` would treat every distinct string as a different person
and split a duo's track record across half-empty rows.

The fix is **`.explode()`**: after `.str.split("|")` each cell holds a *list* of
directors; explode gives every list element its own row (duplicating the movie's
other columns). Each person then gets full credit for each movie they directed,
and `groupby` counts people, not strings.

In [130]:
top_directors = (
    movies.assign(director=movies["director"].str.split("|"))
    .explode("director")
    .groupby("director")
    .agg(
        num_movies=("id", "count"),
        total_revenue=("revenue_musd", "sum"),
        mean_rating=("vote_average", "mean"),
    )
    .sort_values("total_revenue", ascending=False)
    .round(2)
)
top_directors.head(10)

                 num_movies  total_revenue  mean_rating
director
James Cameron             2        5187.87         7.75
Joss Whedon               2        2924.22         7.67
Joe Russo                 1        2799.44         8.24
J.J. Abrams               1        2068.22         7.25
Anthony Russo             1        2052.42         8.24
Colin Trevorrow           1        1671.54         6.70
Jon Favreau               1        1662.02         7.10
James Wan                 1        1515.40         7.22
Jennifer Lee              1        1453.68         7.23
Ryan Coogler              1        1349.93         7.36

 **Next: `04_visualization.ipynb`** — turning these tables into charts.